default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myapp
  password: ENV['MYAPP_DATABASE_PASSWORD']

development:
  <<: *default
  database: cinema_booking_web_app_development

test:
  <<: *default
  database: cinema_booking_web_app_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
